<!--
===============================================================
Name: James Shields
UCID: jfs62
Course: IT-202 Internet Applications (Section XX)
Assignment: Phase 1 – Login/Logout
Store: Guitar Shop
Date: 2025-10-03
Email: jfs62@njit.edu
===============================================================
-->
POST http://localhost:3000/additem.test.php
Content-Type: application/x-www-form-urlencoded


itemID=2000
&itemName=Gibson Les Paul
&categoryID=100
&listPrice=1199.00
###
GET http://localhost:3000/listitems.test.

POST http://localhost:3000/additem.test.php
Content-Type: application/x-www-form-urlencoded


itemID=2000
&itemName=Fender Precision
&categoryID=100
&listPrice=799.99
###
GET http://localhost:3000/listitems.test.php
###
POST http://localhost:3000/changeitem.test.php
Content-Type: application/x-www-form-urlencoded
POST http://localhost:3000/additem.test.php
Content-Type: application/x-www-form-urlencoded

itemID=_2000
&itemName=Fender Precision
&categoryID=100
&listPrice=799.99
###
GET http://localhost:3000/listitems.test.php
###
POST http://localhost:3000/changeitem.test.php
Content-Type: application/x-www-form-urlencoded


itemID=100
&itemName=Fender Precision
&categoryID=100
&listPrice=799.99
###
POST http://localhost:3000/removeitem.test.php
Content-Type: application/x-www-form-urlencoded


itemID=100
